name: CI-CD-Pipeline-to-AWS-ElasticBealstalk
env:
  EB_PACKAGE_S3_BUKET_NAME: "gitgub-actions-s3"
  EB_APPLICATION_NAME:      "MyFlask"
  EB_ENVIROMENT_NAME:       "Myflask-env"
  DEPLOY_PACKAGE_NAME:      "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME:          "us-west-2"

on:
  push:
    branches: 
     - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Create ZIP deployment packages
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region:            ${{ env.AWS_REGION_NAME }}
          
      - name: Copy deployment package to S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUKET_NAME }}/
        
      - name: Print Happy message for CI finish
        run: echo "CI Pipeline part Finished successfully!!!"
        
      - name: Result Zip archived
        run: echo "Zip is archived ${{ env.DEPLOY_PACKAGE_NAME }}"

  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    
    steps:
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region:            ${{ env.AWS_REGION_NAME }}
          
      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name "MyFlask" \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
          
      
      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIROMENT_NAME }} --version-label "Ver-${{ github.sha }}"
        
      - name: Print Happy message for CD finish
        run: echo "CD Pipeline part Finished successfully!!!"
          
          
          
          
          
          
          
          
